[tool.isort]
profile= "black"
multi_line_output= 3
include_trailing_comma= true
force_grid_wrap= 0
use_parentheses= true
line_length= 119

[tool.black]
line-length = 119
target-version = ['py38', 'py39', 'py310', 'py311']
quiet = 0
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
# addopts = "-ra -q --cov=trustllm --disable-pytest-warnings"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.coverage.paths]
source = ["trustllm"]

[tool.coverage.run]
branch = true
source = ["trustllm"]

[tool.coverage.report]
show_missing = true
